#!/usr/bin/env bash

# Simple bash script to make input files for molcas
# Only input xyz file. The rest is default.

out=${1%\.*}.inp
echo $1


echo '&GATEWAY &END'>$out
echo 'TITLE'>>$out
echo 'Generated by subloprop 0.1b'>>$out
echo 'COORD'>>$out
echo ${1}>>$out
echo 'BASIS'>>$out
echo 'A-AUG-CC-PVDZ'>>$out
echo 'GROUP'>>$out
echo 'C1'>>$out
echo 'END OF INPUT'>>$out
echo '&SEWARD &END'>>$out
echo 'MULT'>>$out
echo '2'>>$out
echo 'CHOL'>>$out
echo 'END OF INPUT'>>$out
echo '&SCF &END'>>$out
echo 'CHARGE'>>$out
echo '0'>>$out
echo 'CHOL'>>$out
echo 'KSDFT'>>$out
echo 'B3LYP'>>$out
echo 'END OF INPUT'>>$out
echo '&LOPROP &END'>>$out
echo 'MPPROP'>>$out
echo '2'>>$out
echo 'BONDS'>>$out
echo '0.0'>>$out
echo 'END OF INPUT'>>$out



